AWSTemplateFormatVersion: '2010-09-09'
Description: 'AWS CloudFormation template to create ECR repository'

Resources:
  ECRWebAggregatorRepository:
    Type: 'AWS::ECR::Repository'
    Properties:
      RepositoryName: web-aggregator
      LifecyclePolicy:
        LifecyclePolicyText: !Sub |
          {
            "rules": [
              {
                "rulePriority": 1,
                "description": "Keep only the last 5 images",
                "selection": {
                  "tagStatus": "untagged",
                  "countType": "imageCountMoreThan",
                  "countNumber": 5
                },
                "action": {
                  "type": "expire"
                }
              }
            ]
          }
        RegistryId: !Ref "AWS::AccountId"

  ECRCatalogApiRepository:
    Type: 'AWS::ECR::Repository'
    Properties:
      RepositoryName: catalog-api
      LifecyclePolicy:
        LifecyclePolicyText: !Sub |
          {
            "rules": [
              {
                "rulePriority": 1,
                "description": "Keep only the last 5 images",
                "selection": {
                  "tagStatus": "untagged",
                  "countType": "imageCountMoreThan",
                  "countNumber": 5
                },
                "action": {
                  "type": "expire"
                }
              }
            ]
          }
        RegistryId: !Ref "AWS::AccountId"